### ISSUE TITLE
Add SAFETY comments to unsafe code blocks

### ISSUE THREAD

**Issue by alice-i-cecile** [lee-orr/dexterous_developer#1]
## Which code could be improved?

There's [several places](https://github.com/search?q=repo%3Alee-orr%2Fdexterous_developer%20unsafe&type=code) where unsafe code is used and no justification for why it is sound is listed.

## How should this be changed?

Add `// SAFETY: ` comments, following the Rust ecosystem convention to convince developers that this won't cause surprising and misleading UB while developing.

**Comment by lee-orr** [comment]
Thanks for bringing this to my attention! I was unaware of this convention, and have added those comments here: https://github.com/lee-orr/dexterous_developer/commit/c01ca6680040b9d5eecb12f7bbf9d74c5ac41387 (with the exception of in the fork of bevy_winit, which already has a warning comment)
