### ISSUE TITLE
Dynamic Libraries cant be found with CLI (on certain platforms)

### ISSUE THREAD

**Issue by lee-orr** [lee-orr/dexterous_developer#2]
## Version
0.0.4

## Operating system & version
Linux

## Additional information

Currently a potential solution to this would involve the cargo crate directly for at least the initial compilation of the library, which would allow the CLI to grab the environment info more easily and pass it to the dynamic linker. See for reference: https://github.com/rust-lang/cargo/blob/80eca0e58fb2ff52c1e94fc191b55b37ed73e0e4/src/cargo/core/compiler/compilation.rs#L286

**Comment by lee-orr** [comment]
Updated & released a likely fix in `0.0.6` (https://github.com/lee-orr/dexterous_developer/actions/runs/5944419939) - awaiting feedback from original reporter before closing.

**Comment by wtfamidoingrn** [comment]
I think this bug still persist.
When running dexterous_developer_cli, I get `Error loading library: DlOpen { desc: "libbevy_dylib-15d68d742ee77b1e.so: cannot open shared object file: No such file or directory" }`.

Is there currently any known workaround?

**Comment by lee-orr** [comment]
I did just test a potential workaround, though I can't guarantee it on linux since I've had some issues setting up a linux environment...

What you can do is create a new launcher crate in your workspace, adding a single dependency:
```toml
[dependencies]
dexterous_developer = { version = "0.0.7", default-features = false, features = [
    "hot",
    "cli",
] }
```

and then in `main.rs` for this launcher crate, run the app like so:
```rust
use dexterous_developer::HotReloadOptions;

fn main() {
    dexterous_developer::run_reloadabe_app(HotReloadOptions {
        package: Some("NAME_OF_YOUR_GAME_PACKAGE".to_string()),
        ..Default::default()
    })
}
```

You should then be able to use `cargo run -p launcher` to get the app to run.

**Comment by lee-orr** [comment]
I did add this process to the docs, though they are still building ATM so I replicated it here. LMK i fthat works!

**Comment by lee-orr** [comment]
OK - good to know. In that case, unfortunately I'm not aware of any workarounds ATM. I'm currently working on creating some automated tests that I'd be able to run on linux, mac & CI since so far all my tests were windows based. I'll update here when I have a solution.

**Comment by lee-orr** [comment]
@wtfamidoingrn - It took some time, but I finally think this issue is *actually* resolved, and am able to get automated tests validating it on windows, linux & mac. However, I wanted to ask if you'd be willing to check it in your setup after updating the CLI & dependency to `0.0.8`?

**Comment by lee-orr** [comment]
(Closing for now, will re-open if the issue persists for @wtfamidoingrn)

**Comment by wtfamidoingrn** [comment]
It works perfectly fine now. Thanks alot. 
It took me some time to get things working because I use mold as a linker and I didn't have lld installed and messed things up during installation but that's entirely due to my own

**Comment by lee-orr** [comment]
Awesome! I'm gald it works. I really should add support for mold as well, just haven't used it myself yet... Did the correct error show up letting you know that lld wasn't installed?

As for those errors - they are not a problem, but I can see why they look like an issue. I'll see if I can clean that up, so it doesn't end cause concern.

**Comment by wtfamidoingrn** [comment]
Yes it did say something like "Can't find lld".

**Comment by lee-orr** [comment]
Perfect - thanks! I'll ping you for the next release, which should have mold support. (ATM there's a few other features I want in, but it's already merged)
