### ISSUE TITLE
Unable to get hot reload and full recompile every file the hot reload got triggered?

### ISSUE THREAD

**Issue by ICEFIR** [lee-orr/dexterous_developer#58]
Hey, first thing first, awesome work! 

I am experimenting this package though doesn't quite seems be able to get it to work? not too sure what i did wrong?

## Version

0.2.0

## Operating system & version
Arch Linux (Endevour OS)

## What you did
Setup dexterous_developer according to https://lee-orr.github.io/dexterous_developer/install.html
- cargo install dexterous_developer_cli
- setup Cargo.toml, lib, dependencies etc (attached)
- create a main.rs and corresponding lib.rs
- Execute `dexterous_developer_cli run`

here's the full testing project

[Archive.zip](https://github.com/lee-orr/dexterous_developer/files/15204448/Archive.zip)

## What you expected to happen
- After changing a system - e.g. change its print content, it should hot reload (i think?) and take effect
- Also it should use cached build package & incremental builds

## What actually happened
- After rebuild/reload to complete (the following log appeared), nothing changed, the print system still is printing the old message
```
2024-05-03T19:52:04.492568Z  INFO system{name="bevy_dexterous_developer::hot_internal::reload_systems::update_lib_system"}: dexterous_developer_internal::internal_shared::library_holder: Loaded library
2024-05-03T19:52:04.492637Z  INFO system{name="bevy_dexterous_developer::hot_internal::reload_systems::update_lib_system"}: bevy_dexterous_developer::hot_internal::reload_systems: Got Update
reload complete
```
- The rebuild process is a full rebuild - e.g. the entire project rebuilds, including all the dependencies, not even using build cache. On my full project this would take ~8m, which is way too slow, Also i dont think this is supposed to happen?

## Additional information

[Video recording](https://github.com/lee-orr/dexterous_developer/assets/6231162/8140be0c-043b-4f7f-b8aa-69798f3a8983)

**Comment by ICEFIR** [comment]
For the full recompile issue there is a workaround, which is to keep the cli generated Cargo.toml... that would allow the system to use build cache and incremental build

Not ideal, but useable :)

**Comment by lee-orr** [comment]
For the recompile - often this happens as a result of rust-analyzer - set the rust analyzer cargo.targetDir setting to "true" - which should resolve it.
As for the reload itself not happening - I'll need to look at it in more detail... I'll do that soon.

**Comment by ICEFIR** [comment]
Thanks!

For the recompile i've tried to edit it with Vim only and it still did the full recompile thing... which is weird

**Comment by ICEFIR** [comment]
Okay Thanks!

As for the recompile, editing it using Vim doesn't seems to exhibit the same full recompile behavior.

Also just found out that if i specify `crate-type = ["rlib", "dylib"]` then the recompile issue just disappears. it does increase the output size but ¯\_(ツ)_/¯

**Comment by lee-orr** [comment]
@ICEFIR - the new version (0.3) no longer uses a generated Cargo.toml, it might be worth looking at it if you are updating your project to Bevy 0.14

**Comment by ICEFIR** [comment]
Thanks for the awesome work! will check it out once i port my project to 0.14 (Pending a couple other dependencies at the moment)
